#!/usr/bin/perl

use MATH::Trig;

$TICS_PER_METER = 19685.0;
$MAX_TRACES = 16;
$MAX_SECTIONS = 4096;

#
# Parse data input ino comma separated strings.
#
$jj = 0;
$length = 0.0;
$section_x[0] = 0.0;

while(<>) {

   if(m/^\S+,\s*([0-9\.]+)\,/) {
      $length += $1;
      $section_x[$jj + 1] = $length;
   }
   chomp();
   push(@strings, $_);
   $jj++;
}

$track_length = $length;
$num_sections = $#strings;

#
# Loop through all the sections.
#
foreach $section (0..$num_sections) {
   foreach $trace (0..$MAX_TRACES) {

      #
      # Start function on previous section.
      # Wrap around to the end for first section.
      #
      $jj = $section - 1;
      if($jj < 0) {
	 $jj = $num_sections;
      }

      #
      # 4 values define 4 factors.
      # build up 4x2 matrix
      #
      foreach $x (0..3) {

	 #
	 # Wrap around to start.
	 #
	 if($jj > $num_sections) {
 	    $jj = 0;
	 }

	 @t = split(/, /, $strings[$jj++]);
	 
	 #
	 # Store length, x, and y
	 #
	 $M[$x]{l} = $t[1];
	 $M[$x]{x} = $section_x[$x];
	 if(defined($t[$trace + 2])) {
	    $M[$x]{y} = $t[$trace + 2];
	 }
	 else {
	    $M[$x]{y} = 0;
	 }

	 print "r[$x][$trace] = $M[$x]{x}, Y=$M[$x]{y} L=$M[$x]{l}\n";
      }

      #
      # X locations relative to 0
      #
      foreach $x (0..3) {
         print "$M[$x]{x} $M[$x]{y}\n";
      }
      print "\n\n";

      $slope_left  = ($M[1]{y} - $M[0]{y}) / ($M[1]{x} - $M[0]{x});
      $slope_mid   = ($M[2]{y} - $M[1]{y}) / ($M[2]{x} - $M[1]{x});
      $slope_right = ($M[3]{y} - $M[2]{y}) / ($M[3]{x} - $M[2]{x});

      print "left =  ($M[1]{y} - $M[0]{y}) / ($M[1]{x} - $M[0]{x}) = $slope_left;\n";
      print "mid =   ($M[2]{y} - $M[1]{y}) / ($M[2]{x} - $M[1]{x}) = $slope_mid;\n";
      print "right = ($M[3]{y} - $M[2]{y}) / ($M[3]{x} - $M[2]{x}) = $slope_right;\n";
      

      $S0 = ($slope_mid + $slope_left) / 2.0;
      $SL = ($slope_right + $slope_mid) / 2.0;

      print "S0=$S0\n";
      print "SL=$SL\n";

      $L = $M[2]{x} - $M[1]{x};
      print "L=$L\n";

      $Y0 = $M[1]{y};
      $YL = $M[2]{y};

      $params{d} = $Y0;
      $params{c} = $S0;

      $params{a} = 1.0 / $L**3 * ($L * ($S0 + $SL) + 2.0 * ($Y0 - $YL));
      print "params{a} = 1.0 / $L**3 * ($L * ($S0 + $SL) + 2.0 * ($Y0 - $YL)) = $params{a};\n";

      $params{b} = (1.0 / $L**2) * ($L * (-2.0 * $S0 - $SL) - 3.0 * ($Y0 - $YL));
      print "$params{b} = (1.0 / $L**2) * ($L * (-2.0 * $S0 - $SL) - 3.0 * ($Y0 - $YL)) = $params{b}\n";

      $all_params[$section][$trace]{a} = $params{a};
      $all_params[$section][$trace]{b} = $params{b};
      $all_params[$section][$trace]{c} = $params{c};
      $all_params[$section][$trace]{d} = $params{d};

      $all_geo[$section][$trace]{L} = $M[1]{l};
      $all_geo[$section][$trace]{L_tics} = sprintf("%d", $TICS_PER_METER * $M[1]{l});
      $all_geo[$section][$trace]{X} = $M[1]{x};

      print "f(x) = $params{a}*x**3 +  $params{b}*x**2 +  $params{c}*x +  $params{d}\n";
      print "f(0) = $params{d}\n";

      $f1 =  $params{a} * $M[1]{x}**3 + $params{b} * $M[1]{x}**2 + $params{c} * $M[1]{x} + $params{d};
      print "f($M[1]{x}) = $f1\n";

      foreach $x (0..3) {
         printf("%12g %12g\n", $M[$x]{x}, $M[$x]{y});
      }

      $f0_prime =  $params{c};
      $f1_prime = 3 * $params{a} * $M[2]{x}**2 + 2 * $params{b} * $M[1]{x} + $params{c};

      print "f_prime(0) = $f0_prime\n";
      print "f_prime($M[2]{x}) = $f1_prime\n";
   }
}
 

#
# Create plot file(s) for gnuplot
#
open(PLOT, ">", "__do_plot_all.txt") or
    die "unable to generate data __do_plot_all.txt\n";
    
foreach $section (0..$num_sections) {
   foreach $trace (0 .. $num_traces) {
      print PLOT "f_${section}_${trace}(x) = " .
	  "$all_params[$section][$trace]{a}*x**3 + " .
	  "$all_params[$section][$trace]{b}*x**2 + " .
	  "$all_params[$section][$trace]{c}*x + " .
	  "$all_params[$section][$trace]{d}\n";
   }
}

print PLOT "set xrange [0:$track_length]\n";
print PLOT "plot sample \\\n";


#
# Plot max of 20 sections at a time
#
foreach $x (0..$num_sections) {
   foreach $trace (0..$MAX_TRACES-1) {
      $x_0 = $all_geo[$x][$trace]{X};
      $x_1 = ($all_geo[$x][$trace]{L} + $all_geo[$x][$trace]{X});

      print PLOT "     [${x_0}:${x_1}] f_${x}_${trace}(x-${x_0})"; 

      if($x < $num_sections) {
	 unless($x &&
		(($x % 20) == 0) ||
		($num_sections - x < 20)) {
	    print PLOT ", \\\n";
	 }
      }
   }
   print PLOT "\n";

   if($x && ($x % 20) == 0) {
      print PLOT "pause -1";
      print PLOT "\n";
      print PLOT "\n";
      print PLOT "plot sample \\\n";
   }
}
print PLOT "pause -1";
print PLOT "\n";
print PLOT "\n";

close(PLOT);

open(GTK_TXT, ">", "__gtk_csv.TXT") or
    die "Unable to open __gtk_csv.TXT\n";

#
#
#
foreach $x (0..$num_sections) {

   print GTK_TXT "$x,$all_geo[$x][$trace]{L_tics}";

   #
   #
   #
   foreach $trace (0..$MAX_TRACES-1) {

      #
      # If a coefficient is missing, 0 out all of them.
      #
      unless(defined($all_params[$x][$trace]{a}) &&
	     defined($all_params[$x][$trace]{b}) &&
	     defined($all_params[$x][$trace]{c}) &&
	     defined($all_params[$x][$trace]{d})) {

	 #
	 # Error unless all of them are missing.
	 #
	 if(defined($all_params[$x][$trace]{a}) ||
	    defined($all_params[$x][$trace]{b}) ||
	    defined($all_params[$x][$trace]{c}) ||
	    defined($all_params[$x][$trace]{d})) {

	    print "ERROR 1 or more parameters missing $x/$trace\n";
	    print "A = $all_params[$x][$trace]{a}\n";
	    print "B = $all_params[$x][$trace]{b}\n";
	    print "C = $all_params[$x][$trace]{c}\n";
	    print "D = $all_params[$x][$trace]{d}\n";
	 }

	 $all_params[$x][$trace]{a} = 0;
	 $all_params[$x][$trace]{b} = 0;
	 $all_params[$x][$trace]{c} = 0;
	 $all_params[$x][$trace]{d} = 0;
	 $gradient_angle_0 = "0.0";
      }

      $gradient_angle_0 = sprintf("%.6f", atan2($all_params[$x][$trace]{c}, $all_geo[$x][$trace]{L}));
      if($gradient_angle_0 eq "0.000000") {
	 $gradient_angle_0 = "0.0";
      }

      #
      # Normalize functions for 0->1 domain.
      #
      $L = $all_geo[$x][$trace]{L};
      $a_tics = $L**3 * $all_params[$x][$trace]{a};
      $b_tics = $L**2 * $all_params[$x][$trace]{b};
      $c_tics = $L    * $all_params[$x][$trace]{c};
      $d_tics = $all_params[$x][$trace]{d};
      

      #
      # Formating for floats
      #
      if($a_tics) {
	 $A = sprintf("%.6f", $a_tics);
      } else {
	 $A = 0;
      }

      if($b_tics) {
	 $B = sprintf("%.6f", $b_tics);
      } else {
	 $B = 0;
      }

      if($c_tics) {
	 $C = sprintf("%.6f", $c_tics);
      } else {
	 $C = 0;
      }

      if($d_tics) {
	 $D = sprintf("%.6f", $d_tics);
      } else {
	 $D = 0;
      }

      #
      # CSV for this section/trace
      # 
      print GTK_TXT
	  ",$D," .
	  "$A," .
	  "$B," .
	  "$C," .
	  "$gradient_angle_0";


   }

   print GTK_TXT "\n";
}

close (GTK_TXT);
