#!/usr/bin/perl

#
# Parse data input ino comma separated strings.
#
while(<>) {
    chomp();
    push(@strings, $_);
}

#
# Loop through all the sections.
#
$section = 0;
$track_length = 0;
while($section <= $#strings) {

    #
    # Start function on previous section.
    # Wrap around to the end for first section.
    #
    $jj = $section - 1;
    if($jj < 0) {
	$jj = $#strings;
    }

    #
    # 4 values define 4 factors.
    # build up 4x2 matrix
    #
    foreach $x (0..3) {

	#
	# Wrap around to start.
	#
	if($jj > $#strings) {
 	    $jj = 0;
	}

	@t = split(/,/, $strings[$jj++]);


	#
	# Store length, x, and y
	#
	$M[$x]{l} = $t[0];
	$M[$x]{x} = $t[1];
	$M[$x]{y} = $t[2];

	if($jj == $#strings) {
	    $track_length = $M[$x]{x};
	}

 	print "r[$x] = $M[$x]{x}, $M[$x]{y}\n";
    }

    #
    # Set x relative to 0 for start.
    #
    if($section == 0) {
	$M[0]{x} = -1 * $M[0]{l};
    }

    #
    # Create data file for gnuplot
    #
    open(DATA, ">", "__data.txt") or
	die "unable to generate data __data.txt\n";
    
    $offset = $M[1]{x};
    print "Offset=$offset\n";

    #
    # X locations relative to 0
    #
    foreach $x (0..3) {
	$M[$x]{x} -= $offset;
 	print "s[$x] = $M[$x]{x}, $M[$x]{y}\n";

	print DATA "$M[$x]{x} $M[$x]{y}\n";
       
    }
    close DATA;
    print("\n\n");

    #
    # Call gnuplot to fit equation.
    #
    @results = `gnuplot do_plot.txt |& grep '^[a-d]' | grep '='`;

    #
    # Hunt through program output to find a, b, c, d coefficiants.
    #
    foreach $r (@results) {

	if($r =~ m/^([a-d])\s+=\s+([0-9\.\-e]+)/) {
	    ($X, $n) = ($1, $2);
	    $params{$X} = $n;
	}
    }

    $all_params[$section]{a} = $params{a};
    $all_params[$section]{b} = $params{b};
    $all_params[$section]{c} = $params{c};
    $all_params[$section]{d} = $params{d};

    print "f(x) = $params{a}*x^3 +  $params{b}*x^2 +  $params{c}*x +  $params{d}\n";
    print "f(0) = $params{d}\n";

    $f1 =  $params{a} * $M[1]{x}**3 + $params{b} * $M[1]{x}**2 + $params{c} * $M[1]{x} + $params{d};
    print "f($M[1]{x}) = $f1\n";

    foreach $x (0..3) {
	printf("%12g %12g\n", $M[$x]{x}, $M[$x]{y});
    }

    $f0_prime =  $params{c};
    $f1_prime = 3 * $params{a} * $M[2]{x}**2 + 2 * $params{b} * $M[1]{x} + $params{c};

    print "f_prime(0) = $f0_prime\n";
    print "f_prime($M[2]{x}) = $f1_prime\n";

    $section++
}
 
foreach $x (0..$#strings) {
    print "f_$x(x) = $all_params[$x]{a}*x**3 + $all_params[$x]{b}*x**2 + $all_params[$x]{c}*x + $all_params[$x]{d}\n";
}


foreach $x (0..$#strings) {
    @t = split(/,/, $strings[$jj++]);

    foreach $y (@t) {
	printf "%12g", $y;
    }
    print "\n";
}



      


	  

    
